name = "touchbase-proxy"
main = "worker.ts"
compatibility_date = "2024-03-21"

# Production
[env.production]
vars = { ENVIRONMENT = "production" }

# Route pattern to trigger the worker
routes = [
  { pattern = "api.touchbase.site", custom_domain = true }
]

# Development 
[env.development]
vars = { ENVIRONMENT = "development" }