name = "touchbase-oauth"
main = "worker.ts"
compatibility_date = "2024-03-21"

vars = { ALLOWED_ORIGINS = "https://touchbase.site,https://touchbase-git-staging-ajiteshgogois-projects.vercel.app,http://localhost:5173,http://localhost:3000" }

# Route pattern to trigger the worker
routes = [
  { pattern = "oauth.touchbase.site", custom_domain = true }
]

# Secrets that need to be set:
# - GOOGLE_CLIENT_ID
# - GOOGLE_CLIENT_SECRET
# - WORKER_API_KEY

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true