name: Daily Check

on:
  schedule:
    # Runs every 30 minutes
    - cron: '*/30 * * * *'
  # Allow manual triggers for testing
  workflow_dispatch:

# Add concurrency control to prevent multiple workflows running simultaneously
concurrency:
  group: daily-check
  cancel-in-progress: false

# Security controls
permissions:
  contents: read

env:
  # Batch processing configuration for LLM rate limiting
  BATCH_SIZE: 40                     # Process 40 contacts at a time
  DELAY_BETWEEN_BATCHES: 2000        # Wait 2 seconds between batches to avoid overwhelming the system
  DELAY_BETWEEN_CONTACTS: 1000       # Wait 1 second between contacts in a batch
  MAX_CONTACTS_PER_RUN: 1200           # Limit total contacts per workflow run
  RETRY_ATTEMPTS: 3                   # Number of retries for failed requests
  RETRY_DELAY: 2000                   # Initial delay between retries in milliseconds
  MAX_RETRY_DELAY: 30000              # Maximum delay for exponential backoff in milliseconds
  BACKOFF_MULTIPLIER: 2               # Multiplier for exponential backoff
  RATE_LIMIT_STATUS_CODES: '429,503' # HTTP status codes that indicate rate limiting

jobs:
  verify-security:
    runs-on: ubuntu-latest
    steps:
      - name: Repository check
        if: github.repository != 'ajiteshgogoi/touchbase'
        run: |
          echo "This workflow can only run in ajiteshgogoi/touchbase repository"
          exit 1

      - name: Fork check
        if: github.event_name == 'workflow_dispatch' && github.repository_owner != 'ajiteshgogoi'
        run: |
          echo "Manual workflow execution is only allowed by repository owner ajiteshgogoi"
          exit 1

  run-daily-check:
    needs: verify-security
    runs-on: ubuntu-latest
    timeout-minutes: 45  # Extended timeout for reliable batch processing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build scripts
        run: npm run build:scripts

      - name: Run daily check
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          # Pass batch configuration to the script
          BATCH_SIZE: ${{ env.BATCH_SIZE }}
          DELAY_BETWEEN_BATCHES: ${{ env.DELAY_BETWEEN_BATCHES }}
          DELAY_BETWEEN_CONTACTS: ${{ env.DELAY_BETWEEN_CONTACTS }}
          MAX_CONTACTS_PER_RUN: ${{ env.MAX_CONTACTS_PER_RUN }}
          RETRY_ATTEMPTS: ${{ env.RETRY_ATTEMPTS }}
          RETRY_DELAY: ${{ env.RETRY_DELAY }}
          MAX_RETRY_DELAY: ${{ env.MAX_RETRY_DELAY }}
          BACKOFF_MULTIPLIER: ${{ env.BACKOFF_MULTIPLIER }}
          RATE_LIMIT_STATUS_CODES: ${{ env.RATE_LIMIT_STATUS_CODES }}
        run: node dist/services/daily-check.js