name: Daily Check

on:
  schedule:
    # Runs every 30 minutes
    - cron: '*/30 * * * *'
  # Allow manual triggers for testing
  workflow_dispatch:

jobs:
  trigger-daily-check:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # 1 hour timeout
    steps:
      - name: Trigger Daily Check Function
        run: |
          curl -i --request POST \
          --url 'https://ztsbrysfvmmlxtzoyvle.supabase.co/functions/v1/daily-check' \
          --header 'Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}'