name: Daily Check

on:
  schedule:
    # Runs at 00:00 UTC (5:30 AM IST) every day
    - cron: '0 0 * * *'
  # Allow manual triggers for testing
  workflow_dispatch:

jobs:
  trigger-daily-check:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Daily Check Function
        run: |
          curl -i --request POST \
          --url 'https://ztsbrysfvmmlxtzoyvle.supabase.co/functions/v1/daily-check'