name: Daily Check

on:
  schedule:
    # Runs every 30 minutes
    - cron: '*/30 * * * *'
  # Allow manual triggers for testing
  workflow_dispatch:

env:
  # Batch processing configuration
  BATCH_SIZE: 100                    # Number of contacts per batch
  DELAY_BETWEEN_BATCHES: 5000        # Delay between batches in milliseconds (5 seconds)

jobs:
  run-daily-check:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # 30 minutes timeout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build scripts
        run: npm run build:scripts

      - name: Run daily check
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          BATCH_SIZE: ${{ env.BATCH_SIZE }}
          DELAY_BETWEEN_BATCHES: ${{ env.DELAY_BETWEEN_BATCHES }}
        run: node dist/services/daily-check-v2.js # Updated to use v2 implementation