name: Daily Check

on:
  schedule:
    # Runs every 30 minutes
    - cron: '*/30 * * * *'
  # Allow manual triggers only by repo owner
  workflow_dispatch:

jobs:
  trigger-daily-check:
    # Only run if it's the original repo and either scheduled or triggered by owner
    if: |
      github.repository == 'ajiteshgogoi/touchbase' &&
      (github.event_name == 'schedule' || github.actor == 'ajiteshgogoi')
    runs-on: ubuntu-latest
    timeout-minutes: 60  # 1 hour timeout
    env:
      SUPABASE_URL: https://*****.supabase.co
    steps:
      - name: Verify Repository
        run: |
          if [ "$GITHUB_REPOSITORY" != "ajiteshgogoi/touchbase" ]; then
            echo "Unauthorized repository"
            exit 1
          fi

      - name: Trigger Daily Check Function
        run: |
          echo "Triggering daily check function..."
          OUTPUT=$(curl -s --request POST \
            --url "$SUPABASE_URL/functions/v1/daily-check" \
            --header "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            2>&1) || true
          
          # Only show success/error status without sensitive details
          if [ $? -eq 0 ]; then
            echo "Daily check completed successfully"
          else
            echo "Daily check failed"
          fi